### ISSUE TITLE
Kernel source

### ISSUE THREAD

**Issue by alghiffaryfa19** [YiQiuYes/android_device_xiaomi_enuma#1]
hi, can you share the kernel, vendor and device tree source?

**Comment by YiQiuYes** [comment]
> hi, can you share the kernel, vendor and device tree source?

[vendor](https://github.com/YiQiuYes/android_vendor_xiaomi_enuma)
[device-common](https://github.com/YiQiuYes/android_device_xiaomi_sm8250-common)
[kernel](https://github.com/YiQiuYes/android_device_xiaomi_enuma-kernel-prebuilt)

**Comment by alghiffaryfa19** [comment]
is there anything that is not prebuilt?

**Comment by YiQiuYes** [comment]
you can use lineage's kernel.

**Comment by YiQiuYes** [comment]
but it is very likely that there is a problem of sleeping to death.
